version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: concesionario-blade
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  blade-app:
    build: .
    container_name: blade-container
    depends_on:
      - mysql
    ports:
      - "9001:9001"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/concesionario-blade?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

volumes:
  mysql_data:
